apiVersion: v1
kind: Service
metadata:
  name: wordpress-phpmyadmin
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: phpmyadmin
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-phpmyadmin
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: aht12345
        ports:
        - containerPort: 80
          name: phpmyadmin      
          # volumeMounts:
          #- name: wordpress-persistent-storage
          #mountPath: /var/www/html
          #volumes:
          # - name: wordpress-persistent-storage
          #persistentVolumeClaim:
          # claimName: wp-pv-claim
