apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: wordpress
spec:
  ports:
    - port: 6379
  selector:
    app: wordpress
    tier: redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: wordpress
spec:
        # replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: redis
    spec:
      containers:
      - image: redis:3-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: nginx
          #volumeMounts:
          #- name: nginx-persistent-storage
          #mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"       
            #volumes:
            #- name: wordpress-persistent-storage
            # persistentVolumeClaim:
            #claimName: wp-pv-claim

